mrc-1867 add endpoint to fetch cases averted graph config
mrc-ide/mintr pull request #19
Opened 2020-10-27 20:16 UTC by hillalex

2020-10-28 10:36 UTC, richfitz requested changes
This looks fine except I'm concerned about the incomplete duplication of intervention names. I wonder if we should centralise that all into a json file with the various abbreviations and full names, and reference that within the various schemas? Or in the short term at least be consistent or document being ok with not being consistent

2020-10-28 10:36 UTC, richfitz commented on inst/json/graph_cases_averted_config.json
> +            "tickvals": ["ITN", "PBO", "IRS", "ITN + IRS", "PBO + IRS"],
These intervention names look different to those used in the prevalence graph. We should standardise these somewhere as I feel we're getting a lot of duplication though the code and json here

2020-10-28 10:47 UTC, hillalex commented
> This looks fine except I'm concerned about the incomplete duplication of intervention names. I wonder if we should centralise that all into a json file with the various abbreviations and full names, and reference that within the various schemas? Or in the short term at least be consistent or document being ok with not being consistent

Presuming the intervention names in the prev graph are taken directly from Ellie's data? I'll change this over and document them for now, agree would be nice to auto-populate them somehow. Or perhaps could just write unit tests that validate them against the master list...

2020-10-28 12:20 UTC, hillalex commented
Sorry didn't mean to request review here - this should wait until https://github.com/mrc-ide/mintr/pull/18 is merged and then use the same approach for testing the config.

2020-10-28 15:41 UTC, hillalex commented
Ok, this one now ready for review @richfitz

2020-10-29 10:08 UTC, richfitz approved these changes

2020-10-29 10:08 UTC, merged