mrc-2432 Implement optimiser to strategize across regions
mrc-ide/mintr pull request #57
Opened 2021-06-04 10:01 UTC by mwoodbri

2021-06-07 08:02 UTC, mwoodbri commented on DESCRIPTION
> +    tibble,
This is a dependency of dplyr but it apparently needs to be specified explicitly for `make check`

2021-06-07 08:04 UTC, mwoodbri commented on R/optimise.R
> +#' @import dplyr
This is a short-cut to namespacing every dplyr function (but can do this if preferable)

2021-06-07 08:06 UTC, mwoodbri commented on R/optimise.R
> +utils::globalVariables(c("zone", "intervention", "total_costs", "total_cases_averted", "value", "i", "j"))
Tried to avoid this using `.data$` but it got very verbose, and I still had trouble eliminating all the warnings

2021-06-07 08:08 UTC, mwoodbri commented on tests/testthat/test-optimise.R
> +library(ROI.plugin.glpk)
Not sure of the correct way to do this - it's only required for its side-effects (i.e. loading the plugin), and apparently needs to be done in the context of where the code is invoked, not defined (i.e. it isn't sufficient to put this line in `optimise.R`.

2021-06-07 10:48 UTC, richfitz requested changes

2021-06-07 10:48 UTC, richfitz commented on tests/testthat/test-optimise.R
> +  tibble::tribble(
this is probably the reason why you needed to add tibble to the Suggests?

2021-06-08 13:15 UTC, richfitz approved these changes

2021-06-08 13:15 UTC, merged