mrc-3235 Include pyrrole interventions in Strategise
mrc-ide/mintr pull request #86
Opened 2023-04-03 10:43 UTC by EmmaLRussell

Ensure that pyrrole interventions are included in strategise when `netUse` value is not 0.

2023-04-05 09:42 UTC, EmmaLRussell commented
Any idea what's causing the test coverage failure?

2023-04-05 09:52 UTC, richfitz commented
coverage is failing because that is using a mac builder, I can patch that up if you'd like

2023-04-05 14:55 UTC, richfitz requested changes
actual changes look fine, just a tiny fix to help later

2023-04-05 14:55 UTC, richfitz commented on R/import.R
>    url <- sprintf("%s/%s.tar", root, version)
```suggestion
  root <- "https://github.com/mrc-ide/mintr/releases/download/"
  url <- sprintf("%s/data-%s/%s.tar", root, version, version)
```

though I imagine we'll update the pattern at some point, this is closer to the intent I think

2023-04-13 08:28 UTC, EmmaLRussell commented
Once this gets merged I think we can merge the epic branch since this will work with the newest MINT changes.

2023-04-13 08:30 UTC, EmmaLRussell commented
Ah actually no, we'll want to do this first: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-4149/Fix-mint-for-mintr-epic-branch

2023-04-13 08:35 UTC, richfitz approved these changes

2023-04-13 08:35 UTC, merged